services:
  - type: web
    name: grovi-backend
    env: python
    plan: free
    region: singapore
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port \
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: grovi-db
          property: connectionString
      - key: ALLOWED_ORIGINS
        value: https://grovi-ak7w.vercel.app
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_ALGORITHM
        value: HS256
      # ถ้ามีคีย์อื่น ๆ ให้เพิ่มต่อได้ เช่น GEE_* ฯลฯ

databases:
  - name: grovi-db
